version: '3.8'

services:
  quarkus-web-render-app:
    image: malexj/quarkus_web_render:latest
    pull_policy: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped