name: Quarkus REST app on render

services:
  quarkus-web-render-app:
    image: malexj/quarkus_web_render:latest
    pull_policy: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    mem_limit: 600m
    mem_reservation: 400m
    cpus: 0.75