services:
  quarkus-web-render-app:
    image: malexj/quarkus_web_render:latest
    container_name: quarkus-web-render          # Prevents scaling – see note below
    pull_policy: always                         # Docker Compose v2.20+ supports this
    env_file:
      - .env
    ports:
      - "${PORT:-8189}:${PORT:-8189}"           # Safe fallback
    expose:
      - "8189"                                  # Optional with 'ports', mostly for internal linking
    environment:
      - PORT=8189
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 600m
          cpus: '0.75'
        reservations:
          memory: 400m
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8189/q/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s