quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT}
quarkus.http.root-path=/api/v1
quarkus.smallrye-health.root-path=/health

# Telegram WebApp secret key (uses environment variable APP_SERVICE_TELEGRAM_WEB_APP_SECRET_KEY or defaults to 'secret_key')
webapp.telegram.secret.key=${APP_SERVICE_TELEGRAM_WEB_APP_SECRET_KEY:secret_key}

# Telegram Bot token (uses environment variable APP_SERVICE_TELEGRAM_BOT_TOKEN or defaults to 'fake_token')
webapp.telegram.bot.token=${APP_SERVICE_TELEGRAM_BOT_TOKEN:fake_token}