### Ping Pong
GET http://localhost:8080/api/v1/ping

### Find all tasks
GET http://localhost:8080/api/v1/tasks

###
HEAD http://localhost:8080/api/v1/ping

### BASE Configuration: General health
GET http://localhost:8080/health
