@PORT = 8080

### Find all tasks
GET http://localhost:{{PORT}}/api/v1/tasks


### Create task

POST http://localhost:{{PORT}}/api/v1/tasks
Content-Type: application/json

{
  "name": "Buy groceries",
  "description": "Milk, eggs, bread"
}